development:
  adapter: mysql2
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
  database: base_project_development
  username: root
  password:

test:
  adapter: mysql2
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
  database: base_project_test
  username: root
  password:

production:
  adapter: mysql2
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
  database: base_project_production
  username: root
  password: